export const OLD_JOB_CATEGORIES = [
  {
    id: 1,
    label: "Episodic TV",
    keys: [5, 6, 7, 8],
  },
  {
    id: 2,
    label: "Feature Film",
    keys: [9, 10, 11, 12, 13, 14],
  },
  {
    id: 3,
    label: "Acting",
    keys: [41, 42, 43, 61, 60],
  },
  {
    id: 4,
    label: "Music",
    keys: [28, 29, 30, 31, 32, 33, 44, 45, 46],
  },
  {
    id: 5,
    label: "Dance",
    keys: [3, 4, 53, 54, 55, 56, 57, 58],
  },
  {
    id: 6,
    label: "Crew",
    keys: [16, 25, 34, 35, 36, 37, 38, 39, 40, 47, 48, 49, 50, 51, 52],
  },
  {
    id: 7,
    label: "Modeling",
    keys: [18, 19, 20],
  },
  {
    id: 8,
    label: "Commercials",
    keys: [1],
  },
  {
    id: 9,
    label: "Infomercials",
    keys: [15],
  },
  {
    id: 10,
    label: "Industrial/Training Films",
    keys: [17],
  },
  {
    id: 11,
    label: "Internet",
    keys: [27],
  },
  {
    id: 12,
    label: "Theatre",
    keys: [22, 23],
  },
  {
    id: 13,
    label: "Trade Shows/Live Events/Promo Model",
    keys: [24],
  },
  {
    id: 14,
    label: "Voice-Over",
    keys: [26],
  },
  {
    id: 15,
    label: "Music Videos",
    keys: [21],
  },
  {
    id: 16,
    label: "Reality TV",
    keys: [59],
  },
];

export const JOB_RATE_DES_OBJ: any = {
  0: "",
  1: "event",
  2: "hour",
  3: "day",
  4: "week",
  5: "month",
  6: "negotiable",
};

export const OLD_CATEGORIES_ID_VALUE_OBJ: any = {
  "1": "Commercials",
  "3": "Dance - Ballet/Classic",
  "4": "Dance - Modern/Jazz",
  "5": "Episodic TV - Pilots",
  "6": "Episodic TV - SAG",
  "7": "Episodic TV - AFTRA",
  "8": "Episodic TV - Non-Union",
  "9": "Feature Film - SAG",
  "10": "Feature Film - Non-SAG",
  "11": "Feature Film - Student Films",
  "12": "Feature Film - Short Film",
  "13": "Feature Film - Documentaries",
  "14": "Feature Film - Low Budget/Independent",
  "15": "Infomercials",
  "16": "Crew - Assistant &amp; Entry Level",
  "17": "Industrial/Traning Films",
  "18": "Modeling - Runway",
  "19": "Modeling - Hair/Cosmetics",
  "20": "Modeling - Print",
  "21": "Music Videos",
  "22": "Theatre - Equity (Union)",
  "23": "Theatre - Non-Equity",
  "24": "Trade Shows/Live Events/Promo Model",
  "25": "Crew - Marketing / PR",
  "26": "Voice-Over",
  "27": "Internet",
  "28": "Music - Vocals",
  "29": "Music - Strings",
  "30": "Music - Horns",
  "31": "Music - Keyboards",
  "32": "Music - Drums",
  "33": "Music - Other",
  "34": "Crew - Lighting/Sound",
  "35": "Crew - Camera/Editor",
  "36": "Crew - Producer/Director",
  "37": "Crew - Make Up/ Stylist",
  "38": "Crew - Other",
  "39": "Crew - Writing/Script/Edit",
  "40": "Crew - Showbiz Internship",
  "41": "Acting - Comedy/Clown",
  "42": "Acting - Variety Acts",
  "43": "Acting - Acrobatics/Stunts",
  "44": "Music - Band",
  "45": "Music - DJ/Sound",
  "46": "Music - Teacher",
  "47": "Crew - TV/Radio",
  "48": "Crew - Graphic/Web/Animate",
  "49": "Crew - Acounting/Payroll/HR",
  "50": "Crew - Technology/MIS",
  "51": "Crew - Management",
  "52": "Crew - Talent/Casting Mgmt",
  "53": "Dance - HipHop",
  "54": "Dance - Club/Gogo",
  "55": "Dance - Traditional/Latin",
  "56": "Dance - Choreography",
  "57": "Dance - Teacher",
  "58": "Dance - Other/General",
  "59": "Reality TV",
  "60": "Extras",
  "61": "Acting - Other",
};

export const JOB_SUBMISSION_TYPE_OBJ: any = {
  1: "Self Response",
  2: "Open Call",
};
